Attempt at fixing the deprecation warning from pyflakes
This is based on The-Compiler/pytest-mccabe#8. However, the fix doesn't work,
and I'm not sure how to fix it.

I either get the error

TypeError: from_parent() got an unexpected keyword argument 'flakesignore'

or if I remove flakesignore from the super.from_parent call, I get

TypeError: __init__() missing 1 required positional argument: 'flakesignore'